version: '3'

services:

  db:
    image: mongo:latest
    container_name: db
    restart: unless-stopped
    env_file: .env
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGO_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD=$MONGO_PASSWORD
    volumes:  
      - dbdata:/data/db   

volumes:
  dbdata: